In [1]:
import numpy as np

In [10]:
r = int(input("Enter No of Rows : "))
c = int(input("Enter No of Columns : "))
m1 = np.zeros([r,c])
m2 = np.zeros([r,c])
for i in range (0,r):
    for j in range (0,c):
        m1[i][j]=int(input(f"Enter ({i+1},{j+1}) Element :"))
for i in range (0,r):
    for j in range (0,c):
        m2[i][j]=int(input(f"Enter ({i+1},{j+1}) Element :"))
print(m1)
print(m2)

[[1. 2. 3.]
 [3. 2. 1.]
 [1. 2. 3.]]
[[1. 1. 1.]
 [2. 2. 2.]
 [1. 1. 1.]]


In [14]:
print("Dot Product\n",np.dot(m1,m2))
print("Transpose\n",np.transpose(m1))
print("Rank\n",np.linalg.matrix_rank(m1))


Dot Product
 [[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]
Transpose
 [[1. 3. 1.]
 [2. 2. 2.]
 [3. 1. 3.]]
Rank
 2
