In [3]:
pip install numpy

     |████████████████████████████████| 15.7MB 10.7MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [ ]:
#1.Write  a  NumPy  program  to  create  an  element-wise  comparison  (greater,  greater_equal,  less and less_equal) of two given arrays.

In [39]:
x=np.array([1,2,3,4,5,8])

In [23]:
y=np.array([1,3,6,7,3,5])

In [24]:
print(x)

[1 2 3 4 5]


In [25]:
print(y)

[1 3 6 7 3 5]


In [40]:
print(np.greater(x,y))

[False False False False  True  True]


In [41]:
print(np.greater_equal(x,y))

[ True False False False  True  True]


In [42]:
print(np.less(x,y))

[False  True  True  True False False]


In [43]:
print(np.less_equal(x,y))

[ True  True  True  True False False]


In [ ]:
#2.Write a NumPyprogram to create an array of all the even integers from 30 to 70.

In [30]:
#array=np.arange(start,stop,step) --arange-> ArrayRange

In [ ]:
#array=np.arange(stop) --arange-> Default --- Start = 0 and Step = 1

In [36]:
even30_70=np.arange(30,70,2)

In [37]:
print(even30_70)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [ ]:
#3.Write a NumPy program to create a 3x3 identity matrix.

In [31]:
identity_matrix=np.identity(3)

In [32]:
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4.Write  a  NumPy  program  to  create  a  vector  with  values from  0  to  20 and  change  the  sign  of the numbers in the range from 9 to 15.

In [16]:
vec1=np.arange(21)

In [17]:
vec2=vec1

In [18]:
print("Original Vector")
print("----------------")
print(vec1)

Original Vector
----------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [19]:
vec2[(vec2>=9) & (vec2<=15)]*=-1

In [20]:
print(vec2)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [21]:
print("After Changing Sign")
print("----------------")
print(vec2)      

After Changing Sign
----------------
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [ ]:
#5.Write  a  NumPy  program  to  create  a  5x5  zero  matrix  with  elements  on  the  main  diagonal equal to 1, 2, 3, 4, 5.

In [2]:
diag_matrix=np.zeros((5,5))

In [3]:
np.fill_diagonal(diag_matrix,[1,2,3,4,5])

In [4]:
print(diag_matrix)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [ ]:
#6.Write  a  NumPy  program  to  compute  sum  of  all  elements,  sum  of  each  column  and  sum  of each row of a given array.

In [5]:
test3_array=np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

In [6]:
test3_sum=np.sum(test3_array)

In [7]:
test3_col_sum=np.sum(test3_array,axis=0)

In [8]:
test3_row_sum=np.sum(test3_array,axis=1)

In [22]:
print("Given Array")
print(test3_array)
print("Sum of All Elements : ",test3_sum)
print("Sum of Column Elements : ",test3_col_sum)
print("Sum of Row Elements : ",test3_row_sum)

Given Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of All Elements :  45
Sum of Column Elements :  [12 15 18]
Sum of Row Elements :  [ 6 15 24]


In [ ]:
#7.Write a NumPy program to save a given array to a text file and load it.

In [24]:
np.savetxt("Array1.txt",test3_array,fmt="%d",delimiter=",")

In [26]:
test3_loaded=np.loadtxt("Array1.txt",dtype=int,delimiter=",")

In [27]:
print(test3_loaded)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#8.Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [28]:
Q8_A1=np.array([1,2,3,4])

In [29]:
Q8_A2=np.array([1,2,3,4])

In [30]:
Q8_A3=np.array([1,2,4,5])

In [32]:
print("Array 1 : ",Q8_A1)
print("Array 2 : ",Q8_A2)
print("Array 3 : ",Q8_A3)
print("Array 1 = Array 2 : ",np.array_equal(Q8_A1,Q8_A2))
print("Array 1 = Array 3 : ",np.array_equal(Q8_A1,Q8_A3))

Array 1 :  [1 2 3 4]
Array 2 :  [1 2 3 4]
Array 3 :  [1 2 4 5]
Array 1 = Array 2 :  True
Array 1 = Array 3 :  False


In [ ]:
#9.Write  a  NumPy  program  to  create  a  4x4  array  with  random  values,  now  create  a  new  array from the said array swapping first and last rows.

In [48]:
Q9_Arr=np.array([[1,1,1,1],
                 [2,2,2,2],
                 [3,3,3,3],
                 [4,4,4,4]])

In [54]:
Q9_Arr=np.random.randint(10,size=(4,4))

In [55]:
Q9_Arr_Copy=Q9_Arr.copy()

In [56]:
Q9_Arr_Copy[0],Q9_Arr_Copy[-1]=Q9_Arr_Copy[-1],Q9_Arr_Copy[0]

In [57]:
print("Before")
print(Q9_Arr)
print("\nAfter Swapping 1st and last Rows")
print(Q9_Arr_Copy)

Before
[[5 6 7 3]
 [6 6 3 4]
 [2 2 4 8]
 [3 3 0 7]]

After Swapping 1st and last Rows
[[3 3 0 7]
 [6 6 3 4]
 [2 2 4 8]
 [3 3 0 7]]


In [ ]:
#10.Write a NumPy program to multiply two given arrays of same size element-by-element.

In [58]:
Q10_A=np.array([1,2,3,4])
Q10_B=np.array([4,3,2,1])

In [59]:
Q10_Res=Q10_A*Q10_B

In [61]:
print("Product of ",Q10_A,"&",Q10_B,"\n",Q10_Res)

Product of  [1 2 3 4] & [4 3 2 1] 
 [4 6 6 4]
